### ISSUE TITLE
Previews

### ISSUE THREAD

**Issue by unofficialgfuel** [Aurorum/latin-vocabulary-tester#2]
I believe that when selecting a category (e.g. Verbs 2) there should be some pop-up or preview which presents all the words so it's easier to know what exactly you are selecting.

**Comment by Aurorum** [comment]
Thank you for the idea, I agree that'd be helpful! It's something which I'll work on this month or next once I've thought up a couple design ideas. :)

**Comment by Aurorum** [comment]
Hi @unofficialgfuel, this should be implemented now! You can find it by clicking "View selected words" just beneath the start button. Let me know if there's any issues with it, and thank you very much for the idea! 

<img width="1765" alt="selected-choices" src="https://user-images.githubusercontent.com/43215253/126324251-dd07a1b8-856c-4e18-aa6c-e992f2701b6e.png">

Code: https://github.com/Aurorum/latin-vocabulary-tester/commit/54392949f6fdf2529193d9be62bd0dcf24a86b35

**Comment by unofficialgfuel** [comment]
Looks great! The addition of the removal of words which the user doesn't want/need to learn is also appreciated. No complaints from me.
