### ISSUE TITLE
Dictum:  error reporting the grammatical category of today's word

### ISSUE THREAD

**Issue by ccallawa** [Aurorum/latin-vocabulary-tester#22]
Today's Dictum word:  ēmerō
Reported as:  First person singular active indicative
Should be:  First person singular future perfect indicative
My guess sequence:  omnia > ludet > emero

**Comment by Aurorum** [comment]
Thanks for the bug report! Ah, it looks like I missed a case when checking the verb inflection - I'll get that fixed up now.
