### ISSUE TITLE
Flashcard shows next card translation when on English

### ISSUE THREAD

**Issue by tjmills-dev** [Aurorum/latin-vocabulary-tester#3]
First, thanks so much for this amazing resource - the website mentioned a Discord which sounded interesting but I couldn't find a link.

On the flashcard activity, if the current card is on the English side, clicking the next or previous button will briefly show the English before returning to the Latin side - I'm not sure if this is a bug or a feature.

Edit - made a video to show it:

https://user-images.githubusercontent.com/14115426/153713551-a7df56ed-8e61-4822-bd58-1f48f6222069.mp4

Thanks!

**Comment by Aurorum** [comment]
Thanks! It's not intended and it's something which I've also found annoying when using it myself, but I'm afraid that I haven't been able to figure out a solution to the problem yet. It's something which I plan to take a look at again soon though with hopefully more success - thanks again for the heads up! :)

**Comment by tjmills-dev** [comment]
No problem! Would you prefer the issue closed (if you are already aware of it) or left open?

**Comment by Aurorum** [comment]
Feel free to leave it open and I can keep you updated if/when it's fixed! :)

**Comment by LatinFan123** [comment]
I made some changes to the scripts to fix the bug: please see video

https://user-images.githubusercontent.com/99643027/153827463-4624b54a-91e3-4bbe-8de7-5cfcae1f6ecc.mp4
