### ISSUE TITLE
Add an option to reset incorrect words on test restart

### ISSUE THREAD

**Issue by tjmills-dev** [Aurorum/latin-vocabulary-tester#6]
When restarting a test with incorrect words only, at the end of that test it would be useful to have an option to go over only the words you got wrong on that pass.

I did try to do this so I could submit a PR but I don't really understand the codebase enough :(

**Comment by Aurorum** [comment]
Just closing the loop here by saying that this has now been added. Sorry that it took me so long to implement this - I imagine that it's not much use for you now! However, it might hopefully benefit somebody else, so thanks for the idea. :) 

| Option to remove | Once removed |
|--------|--------|
| <img width="1263" alt="Screenshot 2024-05-19 at 12 16 33" src="https://github.com/Aurorum/latin-vocabulary-tester/assets/43215253/8119cee4-4728-42c7-85a5-d3bd7d66a8cc"> | <img width="1270" alt="Screenshot 2024-05-19 at 12 02 19" src="https://github.com/Aurorum/latin-vocabulary-tester/assets/43215253/a20dde9c-a378-4a92-a5e5-04d0659d6d88"> |
